http_server:
  in_address: ":9090"
elastic_server:
  url: "http://localhost:9200/"
  username: "elastic"
  password: "654321"
timer_server:
  api_notify_min_call_num: 5 # api最少调用次数
  api_notify_ticker: 10 # 健康检测频率
  api_notify_check_time: 240 # 健康检测时长 分钟
  api_notify_all_ticker: 120 # 全检测频率 分钟
  api_notify_check_all_time: 240 # 全检测时长 分钟
  api_notify_wx_key: "7b059317-bbf7-45d7-bb5d-aac6ce5ab416" # 微信通知 key
  delete_index_list: [ "das-test-index" ]
  check_index_list:
    "das-test-index":
      - { "method": "test", "desc": "测试","num": 0 } # 方法，方法名，最少调用次数